### ISSUE TITLE
DatePickerModal Output Format

### ISSUE THREAD

**Issue by abhinay1435** [web-ridge/react-native-paper-dates#100]
Hello Sir,

I need that the date should come in output in format DD/MM/YYYY
I dont want to convert it
Directly it should come in the above format

or is there any good method of conversion

**Comment by mogarick** [comment]
I'd suggest wrapping this component and then in the wrapper you could make the conversion and formatting using a lib such as `date-fns` or some other (I personally don't recommend moment.js because it's huge and I heard is not actively maintained anymore). Then in your app use the wrapper component. This way you could even change the lib in the future if you need or want. 

Components like `react-native-paper-dates` normally manage dates as standard Date objects with a default conversion according to the locale. So if we need to use different format we can convert the date using a lib or we're brave and wild we could make formatting and conversion "by hand" :P

**Comment by RichardLindhout** [comment]
You could use Intl.DateFormat with the same locale and format it.
I won't support this in the library itself.
