### ISSUE TITLE
MM.DD.YYYY needs to be translated

### ISSUE THREAD

**Issue by efkan** [web-ridge/react-native-paper-dates#232]
We should use translated letters for this kind of text. For instance, it should be 'GG.AA.YYYY' and it refers to 'DD.MM.YYYY'.

![image](https://user-images.githubusercontent.com/6974198/210250051-962c6134-86de-4512-a95b-3ae6a9420e68.png)

**Comment by iM-GeeKy** [comment]
PR's welcome!

**Comment by mikib0** [comment]
Hey @iM-GeeKy, I want to work on this. My current idea is to add another property (like dateFormat) to the `translations` object, is that a good approach?

**Comment by iM-GeeKy** [comment]
Hi @mikib0 thanks for wanting to work on this! That approach seems fine and it should be robust enough to accommodate other translations. We will just have to make sure it defaults since the other translations will not have the new property you will be adding. I'm going to rope @RichardLindhout into the discussion, he might have an idea and is much more familiar with the code, which I'm still getting familiar with 🙂.

I see @RichardLindhout put a comment [here](https://github.com/web-ridge/react-native-paper-dates/blob/master/src/Date/dateUtils.tsx#L219) which id assume is one spot where your code change will be.

**Comment by mikib0** [comment]
Yes exactly. Thanks for pointing me there @iM-GeeKy. I am going to make a draft PR and start working on it.

**Comment by RichardLindhout** [comment]
This should be detected automatically using the locale and the INTL implementation. If this does not work in your language it's a bug with intl in react native / ios / android

Have you correctly configured your locale in your language?
