### ISSUE TITLE
Android app crashes in production but not during dev mode

### ISSUE THREAD

**Issue by myt-sheila** [web-ridge/react-native-paper-dates#252]
### Current behaviour
The app crashes as soon as I triggered the button to open the `DatePickerModal` in production, but works fine in expo during development.

I have this in `App.js`
```
import { enGB, registerTranslation } from "react-native-paper-dates";
registerTranslation("en", enGB);
```

And used the modal somewhere like this:
```
 <DatePickerModal
      locale="en"
      mode="range"
      visible={open}
      onDismiss={onDismiss}
      startDate={range.startDate}
      endDate={range.endDate}
      onConfirm={onConfirm}
/>
```

### Expected behaviour
I expected to see the modal exactly like the one I saw during dev mode.

### Your Environment

| software                      | version
| --------------------- | -------
| ios                                | x
| android                        | x
| react-native                | 0.69.6
| react-native-paper    | x.x.x
| node                            | x.x.x
| npm or yarn                | x.x.x
| expo sdk                     | 46.0.0

**Comment by iM-GeeKy** [comment]
Hi @myt-sheila, this is tough to pin down exactly without having a stack trace or error to help better determine what the exact issue is. A few things to try...

- Enable hermes if you haven't done so, this way you won't need to add polyfills
- If you don't have hermes enabled you will need to add polyfills (see https://web-ridge.github.io/react-native-paper-dates/docs/intro#android-caveats).
- Consider adding [sentry](https://docs.expo.dev/guides/using-sentry/) or something of the like, so that you can attempt to get a stack trace of the issue.

**Comment by myt-sheila** [comment]
The app works fine now after enabling `hermes`. In my `app.json`, I specified the values of `jsEngine`:

```
    "jsEngine": "hermes", 
    "ios": {
      ...
      "jsEngine": "hermes"
    },
    "android": {
      ....
      "jsEngine": "hermes"
    }, 
```

Thank you @iM-GeeKy!
