### ISSUE TITLE
DatePickerModal shows weird icons on Android.

### ISSUE THREAD

**Issue by Josh2941** [web-ridge/react-native-paper-dates#371]
### Current behaviour
DatePickerModel shows weird icons when opened on Android using react-native.

### Expected behaviour
DatePickerModel should show proper icons as mentioned in documentation and examples

### How to reproduce?
Follow usual installation as per documentation

### Preview
![Screenshot_1708377915](https://github.com/web-ridge/react-native-paper-dates/assets/34862136/02a63c6d-13e1-4529-8113-af4ae4a9fbc1)

### What have you tried so far?
Tried installing all the fonts from 'react-native-vector-icons'

### Your Environment
"react-native": "0.72.5",
"react-native-paper": "5.12.3",
"react-native-paper-dates": "0.21.9",
"node": "18.16.0"
"yarn":  "1.22.5"

**Comment by RichardLindhout** [comment]
I think you have a strange react-native-vector-icons library installed?

**Comment by RichardLindhout** [comment]
Maybe related too: https://github.com/web-ridge/react-native-paper-dates/issues/370

**Comment by MalgoBlock** [comment]
Just in case someone encounters exactly the same issue on Android (as I have just now): this is due to missing a step in `react-native-vector-icons` setup (please see https://github.com/oblador/react-native-vector-icons), specifically adding `apply from: file("../../node_modules/react-native-vector-icons/fonts.gradle")` into android/app/build.gradle - at least for me it fixed me

**Comment by shuo-hiwintech** [comment]
> 以防万一有人在 Android 上遇到完全相同的问题（就像我刚才遇到的）：这是由于`react-native-vector-icons`设置中缺少一个步骤（请参阅https://github.com/oblador/react-native-vector-icons），特别是添加`apply from: file("../../node_modules/react-native-vector-icons/fonts.gradle")`到 android/app/build.gradle - 至少对我来说它解决了我的问题

Thanks bro, I did overlook that step too hh
