### ISSUE TITLE
Mobile DatePickerModal date format

### ISSUE THREAD

**Issue by airam666** [web-ridge/react-native-paper-dates#63]
The date format in DatePickerModal  is now MM/1/YYYY. tested on Android

**Comment by RichardLindhout** [comment]
If you want something else override the locale and make sure you have set the right timezone in formatjs and check the device language and timezone if it not expected behaviour for that language/locale

**Comment by RichardLindhout** [comment]
Let me know if it's something else :)

**Comment by napzZztar** [comment]
Sorry for re-opening a closed issue. But, I think I'm facing the same problem as @airam666 and don't know how to fix it.

The problem is, when I click on manual date edit button the format shown here is `MM/1/YYYY` which doesn't make any sense to me.

Also, if I try to insert a date in `MM/DD/YYYY` format using keyboard, the module automatically inserts a `/` after the third input digit. So, basically if I type `0102` it becomes `01/0/`.
