### ISSUE TITLE
Takes a while to load dates

### ISSUE THREAD

**Issue by favianca** [web-ridge/react-native-paper-dates#67]
![untitled](https://user-images.githubusercontent.com/50097936/113567457-da50de80-9638-11eb-8bab-100911ee4331.gif)
I am using hermes and polyfill, at first I was using another locale but I changed it back to en but it doesn't seem to fix it. I also thought that it might be the emulator but I have tried on real devices and the problem is still there

**Comment by brunohkbx** [comment]
I was about to open an issue for that :sweat_smile:

This issue is very noticeable in lower-end devices such as iPhone 5s

Example with production bundle
![ezgif com-gif-maker (4)](https://user-images.githubusercontent.com/6487206/113608292-bed9d980-9620-11eb-8b49-1b16690c55fb.gif)

Dev env ( It's taking more than 2s )
![Screenshot from 2021-04-02 11-06-57](https://user-images.githubusercontent.com/6487206/113608709-49bad400-9621-11eb-9943-185f147ca6a4.png)

Is it really necessary to load 4 months at once? wouldn't be better to render only the current one?

**Comment by RichardLindhout** [comment]
Interesting will be a nice case to improve performance since as far as I know I have tried almost every optimisation possible.
I hope React Native Fabric will improve things...

Maybe we can indeed render less on low-end devices but we need to at least render 3 months because it will be too much white when scrolling else.

**Comment by brunohkbx** [comment]
@RichardLindhout how about rendering the current month in the first render and then render the other 3 right after?

I think we could try to wrap a function responsible for rendering the other 3 months with `InteractionManager.runAfterInteractions`

**Comment by favianca** [comment]
@brunohkbx hm that is interesting but in my case I was not loading multiple months as it still load when I change to next month

**Comment by RichardLindhout** [comment]
I think the rendering needs to te be faster as this will bite back when we scroll down

**Comment by RichardLindhout** [comment]
Let's rewrite it in Flutter :-P

**Comment by RichardLindhout** [comment]
Maybe we could detect the performance of the device and edit the amount of months loaded, because I also want fast scrolling so maybe it's a good idea to only 1 month on smaller screens

**Comment by RichardLindhout** [comment]
Indeed we should not need to load 4 months at once, it also seems like the all 4 month are re-rendered when user scrolls while only new ones should reload

**Comment by RichardLindhout** [comment]
I've improved some things in v0.4.4, I would also recommend using Hermes on Android.

**Comment by kendallroth** [comment]
I am using Expo with Hermes (and polyfills) and still seeing very slow loading performance 🤷

**Comment by Jeandcc** [comment]
Is it only on my end, ,or does this continue to be an issue?

**Comment by AviadBag** [comment]
Well still an issue for me..

**Comment by RichardLindhout** [comment]
I think we could optimize using the native view / text directly. See https://github.com/callstack/react-native-paper/issues/4157? cc: @iM-GeeKy
