### ISSUE TITLE
support date-order

### ISSUE THREAD

**Issue by sacru2red** [web-ridge/react-native-paper-dates#93]
use date-order `${year}${yearUnit} ${monthName}` in East-Asia

ex)
2021년 7월 (Korean)
2020年 7月 (Chinese-speaking area)

so i patch like

node_modules/react-native-paper-dates/lib/module/Date/Month.js
```
@@ -205,7 +205,7 @@ function Month(props) {
   }, /*#__PURE__*/React.createElement(Text, {
     style: [styles.monthLabel, theme.fonts.medium],
     selectable: false
-  }, monthName, " ", year), /*#__PURE__*/React.createElement(View, {
+  }, locale === 'ko' ? year + '년' : monthName, " ", locale === 'ko' ? monthName : year), /*#__PURE__*/React.createElement(View, {
```

![date-order](https://user-images.githubusercontent.com/43224844/127624985-e31639ee-d51f-430a-a154-83b9b60e7938.png)

**Comment by RichardLindhout** [comment]
Doesn't it work on iOS out of the box?
It should work out of the box because the Intl api's should fix this.

*Richard Lindhout* | *Eigenaar*
*Bel mij +31 6 43 42 45 67* <+31643424567>

[image: logo webridge]

Beatrixlaan 2, 4694EG Scherpenisse

*KVK      56845367*
*BTW     NL002365659B60*
*IBAN    NL93 BUNQ 2038 9661 33*
*WEB     webRidge.nl <https://webridge.nl/>*




Op vr 30 jul. 2021 om 10:28 schreef sacru2red ***@***.***>:

**Comment by RichardLindhout** [comment]
Hmm maybe we could patch this with an Intl implementation so it works out of the box for all languages.
